# Generated by Django 3.2.4 on 2021-08-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_arquivo', models.IntegerField()),
                ('tipo', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('valor', models.FloatField()),
                ('cpf', models.CharField(max_length=11)),
                ('cartao', models.CharField(max_length=12)),
                ('hora', models.TimeField()),
                ('dono_loja', models.CharField(max_length=14)),
                ('nome_loja', models.CharField(max_length=19)),
            ],
        ),
    ]
