# Generated by Django 3.2.4 on 2021-08-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=25)),
                ('natureza', models.CharField(max_length=25)),
                ('sinal', models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='cnae',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo'),
        ),
    ]
