# Generated by Django 3.2.4 on 2021-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_cnae_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnae',
            name='operacao',
            field=models.CharField(default='', max_length=2),
        ),
    ]
