# Generated by Django 3.2.4 on 2021-08-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_cnae_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnae',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
