# Generated by Django 3.2.4 on 2021-08-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_cnae_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnae',
            name='hora',
            field=models.CharField(default='', max_length=10),
        ),
    ]
